### ISSUE TITLE
Error while starting the webcam.py

### ISSUE THREAD

**Issue by Aaashish11** [mattpoggi/pydnet#6]
python webcam.py --checkpoint_dir checkpoint\IROS18\pydnet --resolution 1
 
I tried running this on Windows 10 and tensorflow 1.8 version.

I got this errors:

2019-03-12 15:04:15.161839: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "webcam.py", line 96, in <module>
    tf.app.run()
  File "C:\Users\Aashish Arora\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "webcam.py", line 78, in main
    toShow = (np.concatenate((img, disp_color), 0)*255.).astype(np.uint8)
ValueError: all the input arrays must have same number of dimensions

**Comment by mattpoggi** [comment]
Hi @Aaashish11 ,
thanks for pointing it out. By indexing img[0] you should fix the problem (see the latest commit)

**Comment by Aaashish11** [comment]
> Hi @Aaashish11 ,
> thanks for pointing it out. By indexing img[0] you should fix the problem (see the latest commit)

Thanks! It is working fine now, after converting width/2 to width//2 as it returned a float value and required was int.

- We wish to apply this concept into android, any guidance for the same will be appreciable! :)
